{{- if not .Values.config.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tautulli-exporter.fullname" . }}
  labels:
    {{- include "tautulli-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ required "either config.apiKey or config.existingSecret.name is required" .Values.config.apiKey | quote }}
{{- end }}
