name: Docker Image CI

on:
 push:
   branches: [ "main" ]
   tags: [ "v*.*.*" ]

env:
 REGISTRY: docker.io
 IMAGE_NAME: mm404/tautulli-exporter

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
       username: mm404
       password: ${{ secrets.DOCKER_HUB_KEY }}

   - name: Extract metadata
     id: meta
     uses: docker/metadata-action@v5
     with:
       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
       tags: |
         type=raw,value=latest,enable={{is_default_branch}}
         type=ref,event=tag
         type=raw,value={{date 'YYYYMMDD'}}-{{sha}},enable={{is_default_branch}}

   - name: Build and push Docker image
     uses: docker/build-push-action@v6
     with:
       context: .
       platforms: linux/amd64,linux/arm64
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
       cache-from: type=gha
       cache-to: type=gha,mode=max
